"""Constants for the clean Freedom House FIW adapter."""

from __future__ import annotations

FREEDOM_HOUSE_SOURCE_KEY = "freedom_house"
FREEDOM_HOUSE_ATTRIBUTION_KEY = "freedom_house"
FREEDOM_HOUSE_DEFAULT_VERSION = "2026"
FREEDOM_HOUSE_HOMEPAGE_URL = "https://freedomhouse.org/report/freedom-world"
FREEDOM_HOUSE_METADATA_NAME = "metadata.json"
FREEDOM_HOUSE_RATINGS_XLSX_NAME = (
    "Country_and_Territory_Ratings_and_Statuses_FIW_1973-2026.xlsx"
)
FREEDOM_HOUSE_RATINGS_ASSET_ID = (
    f"{FREEDOM_HOUSE_SOURCE_KEY}:{FREEDOM_HOUSE_RATINGS_XLSX_NAME}"
)

FREEDOM_HOUSE_OBSERVATION_FAMILY = "political_freedom_country_year"
FREEDOM_HOUSE_SUPPORTED_FAMILIES = (FREEDOM_HOUSE_OBSERVATION_FAMILY,)
FREEDOM_HOUSE_COVERAGE_START_YEAR = 1973
FREEDOM_HOUSE_COVERAGE_END_YEAR = 2026

FREEDOM_HOUSE_COUNTRY_SHEET = "Country Ratings, Statuses "
FREEDOM_HOUSE_TERRITORY_SHEET = "Territory Ratings, Statuses"
FREEDOM_HOUSE_RATING_SHEETS = (
    FREEDOM_HOUSE_COUNTRY_SHEET,
    FREEDOM_HOUSE_TERRITORY_SHEET,
)

FREEDOM_HOUSE_INDICATOR_POLITICAL_RIGHTS = "freedom_house_political_rights"
FREEDOM_HOUSE_INDICATOR_CIVIL_LIBERTIES = "freedom_house_civil_liberties"
FREEDOM_HOUSE_INDICATOR_STATUS = "freedom_house_status"
FREEDOM_HOUSE_INDICATORS = (
    FREEDOM_HOUSE_INDICATOR_POLITICAL_RIGHTS,
    FREEDOM_HOUSE_INDICATOR_CIVIL_LIBERTIES,
    FREEDOM_HOUSE_INDICATOR_STATUS,
)

FREEDOM_HOUSE_ATTRIBUTION_TEXT = (
    "Freedom House, Freedom in the World data (2026 edition), "
    "https://freedomhouse.org/report/freedom-world. Raw database/workbooks "
    "are user-managed and must not be redistributed; cite Freedom House in "
    "derived reports."
)

FREEDOM_HOUSE_TRANSFORM_NAME = "freedom_house_fiw_ratings_statuses_v1"
FREEDOM_HOUSE_CHECKSUM_MISMATCH = "freedom_house_checksum_mismatch"
FREEDOM_HOUSE_LOCAL_FILES_INVALID = "freedom_house_local_files_invalid"
FREEDOM_HOUSE_METADATA_VERSION_MISMATCH = (
    "freedom_house_metadata_version_mismatch"
)
FREEDOM_HOUSE_UNSUPPORTED_VERSION = "unsupported_version"

__all__ = [
    "FREEDOM_HOUSE_ATTRIBUTION_KEY",
    "FREEDOM_HOUSE_ATTRIBUTION_TEXT",
    "FREEDOM_HOUSE_CHECKSUM_MISMATCH",
    "FREEDOM_HOUSE_COUNTRY_SHEET",
    "FREEDOM_HOUSE_COVERAGE_END_YEAR",
    "FREEDOM_HOUSE_COVERAGE_START_YEAR",
    "FREEDOM_HOUSE_DEFAULT_VERSION",
    "FREEDOM_HOUSE_HOMEPAGE_URL",
    "FREEDOM_HOUSE_INDICATORS",
    "FREEDOM_HOUSE_INDICATOR_CIVIL_LIBERTIES",
    "FREEDOM_HOUSE_INDICATOR_POLITICAL_RIGHTS",
    "FREEDOM_HOUSE_INDICATOR_STATUS",
    "FREEDOM_HOUSE_LOCAL_FILES_INVALID",
    "FREEDOM_HOUSE_METADATA_NAME",
    "FREEDOM_HOUSE_METADATA_VERSION_MISMATCH",
    "FREEDOM_HOUSE_OBSERVATION_FAMILY",
    "FREEDOM_HOUSE_RATINGS_ASSET_ID",
    "FREEDOM_HOUSE_RATINGS_XLSX_NAME",
    "FREEDOM_HOUSE_RATING_SHEETS",
    "FREEDOM_HOUSE_SOURCE_KEY",
    "FREEDOM_HOUSE_SUPPORTED_FAMILIES",
    "FREEDOM_HOUSE_TERRITORY_SHEET",
    "FREEDOM_HOUSE_TRANSFORM_NAME",
    "FREEDOM_HOUSE_UNSUPPORTED_VERSION",
]
