"""Tests for the SIPRI Yearbook Ch.7 Stage 2 adapter (REQ-SRC-002).

The SIPRI Yearbook Ch.7 adapter is the sixth Stage 2 adapter built after V-Dem,
WDI, WGI, UCDP, and SIPRI milex. These tests define what "done" means for
the SIPRI Yearbook Ch.7 adapter — they would fail if any of the production
wiring (catalog load, PDF read with Table 7.1 extraction, sentinel coercion,
parquet write, sources upsert, source_observations write, end-to-end
orchestrator) regresses.

SIPRI Yearbook Ch.7 is the FIRST PDF-based source in the pipeline. Every
prior Stage 2 adapter reads xlsx / CSV / zip-CSV / API JSON. This adapter
introduces a new module — sipri_yearbook_ch7_pdf.py — that wraps pdfplumber
to extract Table 7.1 and returns a list of dicts. The rest of the adapter
is the same long→wide pivot pattern as WGI / SIPRI milex.

Tests use a 5-country * 1-year * 3-indicator fixture at
tests/fixtures/sipri_yearbook_ch7/sample.pdf (real-format SIPRI PDF table,
generated by reportlab, no invented values beyond the 3 missing-value
sentinels: "\u2013" for nil/negligible, ".." for not applicable, "c. 24 j"
for circa + footnote). The fixture covers countries United States, Russia,
United Kingdom, France, China for the January 2024 snapshot year.

Key design decisions exercised by these tests:
- SIPRI Yearbook Ch.7 has no ISO3 column; the wide frame's "country"
  column carries the raw SIPRI display name verbatim; source_row_reference
  is "sipri_yearbook_ch7:<display_name>"; Stage 3 resolves to ISO3 via
  country_aliases.csv.
- The PDF has 3 missing-value / annotation tokens: "\u2013" (nil/negligible
  value → 0 in normalized_value), ".." (not applicable → NULL), and
  "c. <num> <letter>" (circa annotation with footnote → parsed integer
  in normalized_value, raw_value preserves the full cell string).
- pdf_pages_total and snapshot_year in SipriYearbookCh7IngestResult are
  the SIPRI-Yearbook-Ch.7 equivalents of UCDP's events_total / events_filtered.
- The source key is "sipri_yearbook_ch7" (already in STAGE2_ADAPTERS as
  a None stub).
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pandas as pd
import pyarrow.parquet as pq
import pytest
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate
from sqlalchemy import func, select
from typer.testing import CliRunner

from leaders_db.cli import app
from leaders_db.db.engine import init_database
from leaders_db.db.models import Source, SourceObservation
from leaders_db.db.session import session_scope
from leaders_db.ingest import STAGE2_ADAPTERS, sipri_yearbook_ch7
from leaders_db.ingest.sipri_yearbook_ch7 import (
    SIPRI_YEARBOOK_CH7_ATTRIBUTION,
    SIPRI_YEARBOOK_CH7_SOURCE_KEY,
    IndicatorSpec,
    SipriYearbookCh7IngestResult,
    attribution,
    default_pdf_path,
    default_processed_parquet_path,
    ingest_sipri_yearbook_ch7,
    load_indicator_catalog,
    read_sipri_yearbook_ch7,
    register_sipri_yearbook_ch7_source,
    write_sipri_yearbook_ch7_observations,
    write_sipri_yearbook_ch7_parquet,
    write_sipri_yearbook_ch7_run_manifest,
)
from leaders_db.ingest.sipri_yearbook_ch7_pdf import read_table_7_1

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture()
def sipri_yearbook_ch7_pdf_dir(isolated_data_lake: Path) -> Path:
    """Stage the SIPRI Yearbook Ch.7 fixture PDF under data/raw/sipri_yearbook_ch7/
    in the test lake.

    Copies the sample PDF to the expected default-pdf path so that
    default_pdf_path() and the orchestrator both find it without an
    explicit pdf_path override.
    """
    target = isolated_data_lake / "data" / "raw" / SIPRI_YEARBOOK_CH7_SOURCE_KEY
    target.mkdir(parents=True, exist_ok=True)

    fixtures_dir = Path(__file__).resolve().parent / "fixtures" / "sipri_yearbook_ch7"
    pdf_name = "YB24 07 WNF.pdf"
    shutil.copy2(fixtures_dir / "sample.pdf", target / pdf_name)

    return target


@pytest.fixture()
def sipri_yearbook_ch7_catalog_path() -> Path:
    """Return the absolute path of the checked-in SIPRI Yearbook Ch.7 indicator catalog.

    Lives at src/leaders_db/ingest/catalogs/sipri_yearbook_ch7.csv relative to project root.
    """
    return (
        Path(__file__).resolve().parents[1]
        / "src"
        / "leaders_db"
        / "ingest"
        / "catalogs"
        / "sipri_yearbook_ch7.csv"
    )


def _init_test_db(database_url: str) -> None:
    """Apply migrations to the test DB so the ORM has its tables."""
    init_database(database_url)


# ---------------------------------------------------------------------------
# Catalog (Phase C convention #5a) — 7 tests
# ---------------------------------------------------------------------------


def test_load_indicator_catalog_returns_3_specs(
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """The checked-in catalog has 3 indicators (matches sipri-yearbook-ch7.md §3.4 spec)."""
    specs = load_indicator_catalog(sipri_yearbook_ch7_catalog_path)
    assert len(specs) == 3, f"Expected 3 indicators, got {len(specs)}"
    assert all(s.variable_name and s.raw_column for s in specs)


def test_load_indicator_catalog_required_columns(
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """The 8 required CSV columns are present; rating_category is 'nuclear'."""
    specs = load_indicator_catalog(sipri_yearbook_ch7_catalog_path)
    categories = {s.rating_category for s in specs}
    assert categories == {"nuclear"}, f"Unexpected categories: {categories}"


def test_load_indicator_catalog_missing_file(tmp_path: Path) -> None:
    """Missing catalog raises FileNotFoundError, not a silent empty list."""
    with pytest.raises(FileNotFoundError):
        load_indicator_catalog(tmp_path / "does-not-exist.csv")


def test_indicator_spec_from_csv_row() -> None:
    """higher_is_better=0/=1 round-trips to a bool (V-Dem/WDI/WGI/UCDP/SIPRI milex pattern)."""
    spec = IndicatorSpec.from_csv_row(
        {
            "variable_name": "sipri_yearbook_ch7_nuclear_warheads_total_inventory",
            "raw_column": "total_inventory",
            "rating_category": "nuclear",
            "raw_scale": "count",
            "normalized_scale_target": "0-1",
            "higher_is_better": "0",
            "unit": "warheads",
            "description": "Total inventory of nuclear warheads.",
        }
    )
    assert spec.higher_is_better is False

    spec_true = IndicatorSpec.from_csv_row(
        {
            "variable_name": "sipri_yearbook_ch7_nuclear_warheads_deployed",
            "raw_column": "deployed",
            "rating_category": "nuclear",
            "raw_scale": "count",
            "normalized_scale_target": "0-1",
            "higher_is_better": "1",
            "unit": "warheads",
            "description": "Deployed nuclear warheads.",
        }
    )
    assert spec_true.higher_is_better is True


def test_catalog_variable_names_match_design(
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """The 3 variable_name values are exactly the names in sipri-yearbook-ch7.md §3.4."""
    specs = load_indicator_catalog(sipri_yearbook_ch7_catalog_path)
    names = {s.variable_name for s in specs}
    expected = {
        "sipri_yearbook_ch7_nuclear_warheads_total_inventory",
        "sipri_yearbook_ch7_nuclear_warheads_deployed",
        "sipri_yearbook_ch7_nuclear_warheads_retired",
    }
    diff_missing = names - expected
    diff_extra = expected - names
    assert names == expected, (
        f"Variable name mismatch: {diff_missing} missing, {diff_extra} extra"
    )


def test_catalog_raw_columns_match_table_keys(
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """The 3 raw_column values are exactly the Table 7.1 column keys:
    total_inventory, deployed, retired."""
    specs = load_indicator_catalog(sipri_yearbook_ch7_catalog_path)
    raw_columns = {s.raw_column for s in specs}
    expected = {"total_inventory", "deployed", "retired"}
    assert raw_columns == expected, (
        f"raw_column mismatch: extra={raw_columns - expected}, missing={expected - raw_columns}"
    )


def test_catalog_retired_is_higher_is_better_false(
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """The retired indicator's higher_is_better is False; the other two are True
    (the disarmament-pipeline inversion per sipri-yearbook-ch7.md §3.4)."""
    specs = load_indicator_catalog(sipri_yearbook_ch7_catalog_path)
    spec_map = {s.raw_column: s for s in specs}
    assert (
        spec_map["retired"].higher_is_better is False
    ), "retired higher_is_better must be False (more retired = more disarmament)"
    assert (
        spec_map["deployed"].higher_is_better is True
    ), "deployed higher_is_better must be True"
    assert (
        spec_map["total_inventory"].higher_is_better is True
    ), "total_inventory higher_is_better must be True"


# ---------------------------------------------------------------------------
# PDF parser (Phase C convention #5b — SIPRI Yearbook Ch.7 specific) — 9 tests
# ---------------------------------------------------------------------------


def test_read_table_7_1_returns_5_country_rows(
    sipri_yearbook_ch7_pdf_dir: Path,
) -> None:
    """The fixture PDF (5 countries + 1 Total aggregate) produces 6 dicts from
    read_table_7_1; the Total row is present and will be filtered out by the
    non-country denylist in the read function."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    rows = read_table_7_1(pdf_path)
    # 5 countries + 1 Total aggregate row
    assert len(rows) == 6, f"Expected 6 rows (5 countries + Total), got {len(rows)}"
    countries = [r["country"] for r in rows]
    assert "Total" in countries, "Total aggregate row must be returned by read_table_7_1"
    assert "United States" in countries
    assert "Russia" in countries
    assert "United Kingdom" in countries
    assert "France" in countries
    assert "China" in countries


def test_read_table_7_1_handles_dash_sentinel(
    sipri_yearbook_ch7_pdf_dir: Path,
) -> None:
    """The en-dash "\u2013" (U+2013) cell in UK's retired becomes 0; raw_value_retired
    preserves the literal "\u2013" (U+2013) for the audit trail."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    rows = read_table_7_1(pdf_path)
    uk = next(r for r in rows if r["country"] == "United Kingdom")
    assert uk["retired"] == 0, (
        f"UK retired '\u2013' must coerce to 0, got {uk['retired']!r}"
    )
    assert (
        uk["raw_value_retired"] == "\u2013"
    ), f"raw_value_retired must preserve '\u2013', got {uk['raw_value_retired']!r}"


def test_read_table_7_1_handles_dots_sentinel(
    sipri_yearbook_ch7_pdf_dir: Path,
) -> None:
    """The ".." cell in France's retired becomes None; raw_value_retired
    preserves the literal ".." for the audit trail."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    rows = read_table_7_1(pdf_path)
    france = next(r for r in rows if r["country"] == "France")
    assert (
        france["retired"] is None
    ), f"France retired '..' must coerce to None, got {france['retired']!r}"
    assert (
        france["raw_value_retired"] == ".."
    ), f"raw_value_retired must preserve '..', got {france['raw_value_retired']!r}"


def test_read_table_7_1_handles_c_prefix(
    sipri_yearbook_ch7_pdf_dir: Path,
) -> None:
    """The "c. 24 j" cell in China's deployed becomes 24; raw_value_deployed
    preserves the literal "c. 24 j" for the audit trail."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    rows = read_table_7_1(pdf_path)
    china = next(r for r in rows if r["country"] == "China")
    assert china["deployed"] == 24, (
        f"China deployed 'c. 24 j' must coerce to 24, got {china['deployed']!r}"
    )
    assert (
        china["raw_value_deployed"] == "c. 24 j"
    ), f"raw_value_deployed must preserve 'c. 24 j', got {china['raw_value_deployed']!r}"


def test_read_table_7_1_strips_footnote_letter(
    sipri_yearbook_ch7_pdf_dir: Path,
) -> None:
    """The footnote letter (j in "c. 24 j") is stripped from the parsed integer;
    the parsed value is 24, not "24 j"."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    rows = read_table_7_1(pdf_path)
    china = next(r for r in rows if r["country"] == "China")
    # The footnote letter j must not appear in the parsed integer
    assert china["deployed"] == 24
    assert isinstance(china["deployed"], int)
    assert not str(china["deployed"]).endswith("j")
    assert not str(china["deployed"]).startswith("c.")


def test_read_table_7_1_recomputed_totals_match(
    sipri_yearbook_ch7_pdf_dir: Path,
) -> None:
    """The recomputed stockpile_total (= deployed + stored) and total_inventory
    (= stockpile_total + retired) match the published values for all 5 countries
    (no warning should be logged by the read function's sanity check)."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    rows = read_table_7_1(pdf_path)
    for r in rows:
        if r["country"] == "Total":
            continue
        deployed = r["deployed"] if r["deployed"] is not None else 0
        stored = r["stored"] if r["stored"] is not None else 0
        retired = r["retired"] if r["retired"] is not None else 0
        recomputed_stockpile = deployed + stored
        recomputed_total = recomputed_stockpile + retired
        assert (
            recomputed_stockpile == r["stockpile_total"]
        ), (
            f"{r['country']}: stockpile_total mismatch: "
            f"{recomputed_stockpile} vs {r['stockpile_total']}"
        )
        assert (
            recomputed_total == r["total_inventory"]
        ), f"{r['country']}: total_inventory mismatch: {recomputed_total} vs {r['total_inventory']}"


def test_read_table_7_1_preserves_raw_values(
    sipri_yearbook_ch7_pdf_dir: Path,
) -> None:
    """The 5 raw_value_<col> keys are present in each dict and preserve the
    original PDF cell verbatim."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    rows = read_table_7_1(pdf_path)
    for r in rows:
        if r["country"] == "Total":
            continue
        for col_key in ["deployed", "stored", "stockpile_total", "retired", "total_inventory"]:
            raw_key = f"raw_value_{col_key}"
            assert raw_key in r, f"{r['country']} missing {raw_key}"
            assert r[raw_key] is not None, f"{r['country']} {raw_key} must not be None"
            assert isinstance(r[raw_key], str), f"{r['country']} {raw_key} must be str"


def test_read_table_7_1_missing_pdf(tmp_path: Path) -> None:
    """Missing PDF raises FileNotFoundError."""
    with pytest.raises(FileNotFoundError):
        read_table_7_1(tmp_path / "nonexistent.pdf")


def test_read_table_7_1_table_not_found(tmp_path: Path) -> None:
    """A PDF without Table 7.1 raises ValueError (the table-search logic fails
    on the first 3 pages and raises an actionable message)."""
    # A plain text PDF with no tables at all — pdfplumber's lines strategy
    # returns 0 tables; the text fallback also returns 0 tables; the parser
    # raises RuntimeError which the read wrapper re-raises as ValueError.
    stub_pdf = tmp_path / "no_table.pdf"
    style = getSampleStyleSheet()["Normal"]
    SimpleDocTemplate(str(stub_pdf), pagesize=A4).build(
        [Paragraph("Chapter 7. No tables here.", style)]
    )
    with pytest.raises(ValueError, match=r"Table 7\.1"):
        read_table_7_1(stub_pdf)


# ---------------------------------------------------------------------------
# Read (Phase C convention #5b) — 8 tests
# ---------------------------------------------------------------------------


def test_read_sipri_yearbook_ch7_returns_full_fixture(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """The fixture (5 countries * 1 year * 3 indicators) produces a wide DataFrame:
    5 rows (countries), 5 columns (country, year, 3 indicator columns)."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    assert len(df) == 5, f"Expected 5 country-year rows, got {len(df)}"
    expected_cols = {
        "country",
        "year",
        "sipri_yearbook_ch7_nuclear_warheads_total_inventory",
        "sipri_yearbook_ch7_nuclear_warheads_deployed",
        "sipri_yearbook_ch7_nuclear_warheads_retired",
    }
    assert set(df.columns) == expected_cols, f"Column mismatch: {set(df.columns)}"
    assert pd.api.types.is_integer_dtype(df["year"])


def test_read_sipri_yearbook_ch7_filters_to_year(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """year=2024 keeps only the 5 country-year rows for 2024;
    set(df["year"]) == {2024}."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(
        year=2024, pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path,
    )
    assert set(df["year"].unique()) == {2024}
    assert len(df) == 5


def test_read_sipri_yearbook_ch7_filters_to_other_year_returns_empty(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """year=2023 (an out-of-snapshot year) returns an empty DataFrame;
    the YB24 fixture has only 2024."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(
        year=2023, pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path,
    )
    assert len(df) == 0, f"Expected empty DataFrame for year=2023, got {len(df)} rows"


def test_read_sipri_yearbook_ch7_filters_total_row(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """The Total aggregate row is NOT in the wide frame; only the 5 P5 countries
    remain; set(df["country"]) == {"United States", "Russia", "United Kingdom",
    "France", "China"}."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    expected_countries = {
        "United States",
        "Russia",
        "United Kingdom",
        "France",
        "China",
    }
    assert set(df["country"].unique()) == expected_countries
    assert "Total" not in df["country"].values


def test_read_sipri_yearbook_ch7_pivots_long_to_wide(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """Each catalog indicator is one column; no row is duplicated; no
    (country, indicator) cell is in long format."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    assert len(df.drop_duplicates(subset=["country", "year"])) == len(df)
    assert "variable_name" not in df.columns
    for col in [
        "sipri_yearbook_ch7_nuclear_warheads_total_inventory",
        "sipri_yearbook_ch7_nuclear_warheads_deployed",
        "sipri_yearbook_ch7_nuclear_warheads_retired",
    ]:
        assert col in df.columns


def test_read_sipri_yearbook_ch7_handles_dash_sentinel(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """The en-dash "\u2013" cell in UK's retired becomes 0 in the DataFrame's
    sipri_yearbook_ch7_nuclear_warheads_retired column (pd.NA is NOT used
    for nil/negligible - the SIPRI legend distinguishes "\u2013" from "..")."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    uk = df[df["country"] == "United Kingdom"]
    assert len(uk) == 1
    assert not pd.isna(uk["sipri_yearbook_ch7_nuclear_warheads_retired"].iloc[0])
    assert int(uk["sipri_yearbook_ch7_nuclear_warheads_retired"].iloc[0]) == 0


def test_read_sipri_yearbook_ch7_handles_dots_sentinel(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """The ".." cell in France's retired becomes pd.NA (nullable Int64) in the
    DataFrame's sipri_yearbook_ch7_nuclear_warheads_retired column."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    france = df[df["country"] == "France"]
    assert len(france) == 1
    assert pd.isna(france["sipri_yearbook_ch7_nuclear_warheads_retired"].iloc[0])


def test_read_sipri_yearbook_ch7_handles_c_prefix(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """The "c. 24 j" cell in China's deployed becomes 24 in the DataFrame's
    sipri_yearbook_ch7_nuclear_warheads_deployed column."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    china = df[df["country"] == "China"]
    assert len(china) == 1
    assert int(china["sipri_yearbook_ch7_nuclear_warheads_deployed"].iloc[0]) == 24


def test_read_sipri_yearbook_ch7_attrs_carry_pdf_pages_and_snapshot_year(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """df.attrs carries pdf_pages_total (1 for the 1-page fixture) and
    snapshot_year (2024 for YB24)."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    assert "pdf_pages_total" in df.attrs, "df.attrs must carry pdf_pages_total"
    assert "snapshot_year" in df.attrs, "df.attrs must carry snapshot_year"
    assert df.attrs["pdf_pages_total"] == 1, "Fixture PDF is 1 page"
    assert df.attrs["snapshot_year"] == 2024, "YB24 fixture snapshot year is 2024"


def test_read_sipri_yearbook_ch7_missing_pdf(
    sipri_yearbook_ch7_catalog_path: Path,
    tmp_path: Path,
) -> None:
    """Missing PDF raises FileNotFoundError."""
    with pytest.raises(FileNotFoundError):
        read_sipri_yearbook_ch7(
            pdf_path=tmp_path / "missing.pdf",
            catalog_path=sipri_yearbook_ch7_catalog_path,
        )


def test_default_path_helpers(isolated_data_lake: Path) -> None:
    """default_pdf_path() points at data/raw/sipri_yearbook_ch7/YB24 07 WNF.pdf;
    raises FileNotFoundError if missing. default_processed_parquet_path() points
    at data/processed/sipri_yearbook_ch7/sipri_yearbook_ch7_country_year.parquet."""
    sipri_dir = isolated_data_lake / "data" / "raw" / SIPRI_YEARBOOK_CH7_SOURCE_KEY
    sipri_dir.mkdir(parents=True, exist_ok=True)
    pdf_file = sipri_dir / "YB24 07 WNF.pdf"
    pdf_file.touch()

    pdf_default = default_pdf_path()
    assert pdf_default.name == "YB24 07 WNF.pdf"
    assert SIPRI_YEARBOOK_CH7_SOURCE_KEY in pdf_default.parts

    parquet_default = default_processed_parquet_path()
    assert parquet_default.name == "sipri_yearbook_ch7_country_year.parquet"
    assert SIPRI_YEARBOOK_CH7_SOURCE_KEY in parquet_default.parts


# ---------------------------------------------------------------------------
# Parquet write + DB (Phase C convention #5c) — 7 tests
# ---------------------------------------------------------------------------


def test_write_sipri_yearbook_ch7_parquet_creates_file(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    isolated_data_lake: Path,
) -> None:
    """write_sipri_yearbook_ch7_parquet(df) writes a valid parquet under
    data/processed/sipri_yearbook_ch7/; round-trip preserves shape and columns."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    out = write_sipri_yearbook_ch7_parquet(df)

    assert out.exists()
    assert out.suffix == ".parquet"
    expected_parent = isolated_data_lake / "data" / "processed" / SIPRI_YEARBOOK_CH7_SOURCE_KEY
    assert out.parent == expected_parent

    round_tripped = pd.read_parquet(out)
    assert round_tripped.shape == df.shape
    assert set(round_tripped.columns) == set(df.columns)


def test_write_sipri_yearbook_ch7_parquet_attaches_attribution_metadata(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
) -> None:
    """The parquet file-level metadata carries sipri_yearbook_ch7_attribution
    (byte-for-byte SIPRI_YEARBOOK_CH7_ATTRIBUTION) and sipri_yearbook_ch7_source_key."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    out = write_sipri_yearbook_ch7_parquet(df)
    table = pq.read_table(out)
    meta = table.schema.metadata or {}

    attribution_bytes = meta.get(b"sipri_yearbook_ch7_attribution")
    assert attribution_bytes is not None, "parquet missing sipri_yearbook_ch7_attribution metadata"
    assert attribution_bytes.decode("utf-8") == SIPRI_YEARBOOK_CH7_ATTRIBUTION
    assert meta.get(b"sipri_yearbook_ch7_source_key") == b"sipri_yearbook_ch7"


def test_register_sipri_yearbook_ch7_source_is_idempotent(
    sipri_yearbook_ch7_pdf_dir: Path,
    database_url: str,
) -> None:
    """Two calls to register_sipri_yearbook_ch7_source return the same id.

    Row has source_name='SIPRI Yearbook Chapter 7 (World Nuclear Forces)',
    version='YB2024 (data: January 2024)', source_type='academic'.
    """
    _init_test_db(database_url)
    with session_scope(database_url) as session:
        first_id = register_sipri_yearbook_ch7_source(session)
    with session_scope(database_url) as session:
        second_id = register_sipri_yearbook_ch7_source(session)
    assert first_id == second_id, "register_sipri_yearbook_ch7_source should be idempotent"

    with session_scope(database_url) as session:
        row = session.execute(select(Source).where(Source.id == first_id)).scalar_one()
        assert row.source_name == "SIPRI Yearbook Chapter 7 (World Nuclear Forces)"
        assert row.version == "YB2024 (data: January 2024)"
        assert row.source_type == "academic"


def test_register_sipri_yearbook_ch7_source_non_destructive_update(
    sipri_yearbook_ch7_pdf_dir: Path,
    database_url: str,
) -> None:
    """Removing metadata.json between calls keeps existing source_url and
    license_note (same policy as V-Dem/WDI/WGI/UCDP/SIPRI milex)."""
    _init_test_db(database_url)
    with session_scope(database_url) as session:
        first_id = register_sipri_yearbook_ch7_source(session)
    with session_scope(database_url) as session:
        first = session.execute(select(Source).where(Source.id == first_id)).scalar_one()
        first_url = first.source_url
        first_license = first.license_note

    bundle_meta = sipri_yearbook_ch7_pdf_dir / "metadata.json"
    if bundle_meta.is_file():
        bundle_meta.unlink()

    with session_scope(database_url) as session:
        second_id = register_sipri_yearbook_ch7_source(session)
    assert first_id == second_id
    with session_scope(database_url) as session:
        second = session.execute(select(Source).where(Source.id == second_id)).scalar_one()
        assert second.source_url == first_url
        assert second.license_note == first_license


def test_write_sipri_yearbook_ch7_observations_row_count(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """len(df) * len(specs) observations are written. With the fixture
    (5 rows * 3 indicators) the count is 15."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    specs = load_indicator_catalog(sipri_yearbook_ch7_catalog_path)
    expected_rows = len(df) * len(specs)  # 5 * 3 = 15

    with session_scope(database_url) as session:
        source_id = register_sipri_yearbook_ch7_source(session)
        rows_written = write_sipri_yearbook_ch7_observations(
            session, source_id, df, catalog_path=sipri_yearbook_ch7_catalog_path,
        )
    assert rows_written == expected_rows

    with session_scope(database_url) as session:
        count = session.execute(
            select(func.count(SourceObservation.id)).where(
                SourceObservation.source_id == source_id
            )
        ).scalar_one()
    assert count == expected_rows


def test_write_sipri_yearbook_ch7_observations_is_idempotent(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """Re-running write_sipri_yearbook_ch7_observations produces the same count,
    not 2* the count."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    specs = load_indicator_catalog(sipri_yearbook_ch7_catalog_path)
    expected_rows = len(df) * len(specs)

    with session_scope(database_url) as session:
        source_id = register_sipri_yearbook_ch7_source(session)
        write_sipri_yearbook_ch7_observations(
            session, source_id, df, catalog_path=sipri_yearbook_ch7_catalog_path,
        )
    with session_scope(database_url) as session:
        write_sipri_yearbook_ch7_observations(
            session, source_id, df, catalog_path=sipri_yearbook_ch7_catalog_path,
        )

    with session_scope(database_url) as session:
        count = session.execute(
            select(func.count(SourceObservation.id)).where(
                SourceObservation.source_id == source_id
            )
        ).scalar_one()
    assert count == expected_rows


def test_write_sipri_yearbook_ch7_observations_country_id_is_null(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """Stage 2 leaves country_id NULL (Stage 3 fills it); confidence is NULL
    (Stage 11 fills it); source_row_reference starts with 'sipri_yearbook_ch7:'
    and carries the display name verbatim."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    specs = load_indicator_catalog(sipri_yearbook_ch7_catalog_path)

    with session_scope(database_url) as session:
        source_id = register_sipri_yearbook_ch7_source(session)
        write_sipri_yearbook_ch7_observations(
            session, source_id, df, catalog_path=sipri_yearbook_ch7_catalog_path,
        )

    with session_scope(database_url) as session:
        rows = session.execute(
            select(SourceObservation).where(SourceObservation.source_id == source_id)
        ).scalars().all()

    assert len(rows) == len(df) * len(specs)
    assert all(r.country_id is None for r in rows)
    assert all(r.leader_id is None for r in rows)
    assert all(r.confidence is None for r in rows), (
        "confidence must be NULL for all SIPRI Yearbook Ch.7 rows (Stage 11 fills it)"
    )
    assert all(
        r.source_row_reference and r.source_row_reference.startswith("sipri_yearbook_ch7:")
        for r in rows
    ), "source_row_reference must start with 'sipri_yearbook_ch7:'"


def test_write_sipri_yearbook_ch7_observations_handles_dash_sentinel(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """A "\u2013" row (UK's retired) becomes normalized_value=0 in SQLite;
    raw_value is the literal "\u2013" (U+2013)."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)

    with session_scope(database_url) as session:
        source_id = register_sipri_yearbook_ch7_source(session)
        write_sipri_yearbook_ch7_observations(
            session, source_id, df, catalog_path=sipri_yearbook_ch7_catalog_path,
        )

    with session_scope(database_url) as session:
        rows = session.execute(
            select(SourceObservation).where(
                SourceObservation.source_id == source_id,
                SourceObservation.variable_name
                == "sipri_yearbook_ch7_nuclear_warheads_retired",
                SourceObservation.source_row_reference == "sipri_yearbook_ch7:United Kingdom",
                SourceObservation.year == 2024,
            )
        ).scalars().all()

    assert len(rows) == 1
    assert rows[0].normalized_value == 0, (
        "normalized_value must be 0 for '\u2013' nil sentinel"
    )
    assert rows[0].raw_value == "\u2013", (
        f"raw_value must be the literal '\u2013', got {rows[0].raw_value!r}"
    )


def test_write_sipri_yearbook_ch7_observations_handles_dots_sentinel(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """A ".." row (France's retired) becomes normalized_value=NULL in SQLite;
    raw_value is the literal ".."."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)

    with session_scope(database_url) as session:
        source_id = register_sipri_yearbook_ch7_source(session)
        write_sipri_yearbook_ch7_observations(
            session, source_id, df, catalog_path=sipri_yearbook_ch7_catalog_path,
        )

    with session_scope(database_url) as session:
        rows = session.execute(
            select(SourceObservation).where(
                SourceObservation.source_id == source_id,
                SourceObservation.variable_name
                == "sipri_yearbook_ch7_nuclear_warheads_retired",
                SourceObservation.source_row_reference == "sipri_yearbook_ch7:France",
                SourceObservation.year == 2024,
            )
        ).scalars().all()

    assert len(rows) == 1
    assert rows[0].normalized_value is None, (
        "normalized_value must be NULL for '..' not-applicable sentinel"
    )
    assert rows[0].raw_value == "..", (
        f"raw_value must be the literal '..', got {rows[0].raw_value!r}"
    )


def test_write_sipri_yearbook_ch7_observations_handles_c_prefix(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """A "c. 24 j" row (China's deployed) becomes normalized_value=24 in SQLite;
    raw_value is the literal "c. 24 j" (preserving the circa prefix and footnote
    letter for the audit trail)."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)

    with session_scope(database_url) as session:
        source_id = register_sipri_yearbook_ch7_source(session)
        write_sipri_yearbook_ch7_observations(
            session, source_id, df, catalog_path=sipri_yearbook_ch7_catalog_path,
        )

    with session_scope(database_url) as session:
        rows = session.execute(
            select(SourceObservation).where(
                SourceObservation.source_id == source_id,
                SourceObservation.variable_name
                == "sipri_yearbook_ch7_nuclear_warheads_deployed",
                SourceObservation.source_row_reference == "sipri_yearbook_ch7:China",
                SourceObservation.year == 2024,
            )
        ).scalars().all()

    assert len(rows) == 1
    assert rows[0].normalized_value == 24, (
        "normalized_value must be 24 for 'c. 24 j' circa annotation"
    )
    assert rows[0].raw_value == "c. 24 j", (
        f"raw_value must preserve 'c. 24 j', got {rows[0].raw_value!r}"
    )


def test_write_sipri_yearbook_ch7_observations_preserves_raw_value(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """raw_value is the stringified int for non-missing cells (e.g., "5044" for
    USA's total_inventory); raw_value is the literal "\u2013"/".."/"c. 24 j" for
    cells with the corresponding sentinels."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)

    with session_scope(database_url) as session:
        source_id = register_sipri_yearbook_ch7_source(session)
        write_sipri_yearbook_ch7_observations(
            session, source_id, df, catalog_path=sipri_yearbook_ch7_catalog_path,
        )

    with session_scope(database_url) as session:
        rows = session.execute(
            select(SourceObservation).where(
                SourceObservation.source_id == source_id,
                SourceObservation.variable_name
                == "sipri_yearbook_ch7_nuclear_warheads_total_inventory",
            )
        ).scalars().all()

    for r in rows:
        assert r.raw_value is not None, (
            f"raw_value for {r.source_row_reference}/{r.year} must not be NULL"
        )
        assert r.raw_value != "", (
            f"raw_value for {r.source_row_reference}/{r.year} must not be empty"
        )
        # For non-missing cells, raw_value is the stringified int (the audit
        # promise: every non-missing observation in this table has a plain
        # numeric raw cell that round-trips through str(int) → int). If a
        # future iteration ever preserves the literal PDF cell text (e.g.
        # "1 770 d" with thousands separator + footnote letter) for a
        # non-missing row, this branch must catch the regression rather than
        # raise ValueError from int().
        if r.normalized_value is not None:
            try:
                raw_as_int = int(r.raw_value)  # type: ignore[arg-type]
            except ValueError:
                pytest.fail(
                    f"raw_value {r.raw_value!r} for "
                    f"{r.source_row_reference}/{r.year} is not a plain numeric "
                    f"string, but normalized_value={r.normalized_value}; the "
                    "audit promise is that non-missing cells round-trip "
                    "str(int(value)) ↔ int."
                )
            assert (
                str(r.normalized_value) == r.raw_value
                or raw_as_int == r.normalized_value
            ), (
                f"raw_value {r.raw_value!r} should match normalized_value {r.normalized_value}"
            )


# ---------------------------------------------------------------------------
# Orchestrator (Phase C convention #5d — end-to-end idempotency) — 5 tests
# ---------------------------------------------------------------------------


def test_ingest_sipri_yearbook_ch7_end_to_end(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """ingest_sipri_yearbook_ch7() writes parquet + observations + sources + manifest
    in one call. Full fixture: 5 countries * 1 year * 3 indicators = 15 rows.
    The SipriYearbookCh7IngestResult has 8 fields: source_id, parquet_path,
    observation_rows, countries, years, indicators, pdf_pages_total, snapshot_year."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    result = ingest_sipri_yearbook_ch7(
        pdf_path=pdf_path,
        catalog_path=sipri_yearbook_ch7_catalog_path,
    )

    assert isinstance(result.parquet_path, Path)
    assert result.parquet_path.exists()
    assert result.source_id > 0
    assert result.observation_rows == 15  # 5 * 3
    assert result.countries == 5
    assert result.years == (2024,)
    assert result.indicators == 3
    assert result.pdf_pages_total == 1  # fixture PDF is 1 page
    assert result.snapshot_year == 2024
    # Attribution on result
    assert result.attribution == SIPRI_YEARBOOK_CH7_ATTRIBUTION
    # Run manifest auto-written
    manifest = result.parquet_path.parent / "sipri_yearbook_ch7_run_manifest.json"
    assert manifest.exists()
    manifest_payload = json.loads(manifest.read_text(encoding="utf-8"))
    assert manifest_payload["attribution"] == SIPRI_YEARBOOK_CH7_ATTRIBUTION
    assert manifest_payload["observation_rows"] == 15
    assert manifest_payload["years"] == [2024]
    assert manifest_payload["indicators"] == 3
    assert manifest_payload["pdf_pages_total"] == 1
    assert manifest_payload["snapshot_year"] == 2024


def test_ingest_sipri_yearbook_ch7_filters_to_year(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """year=2024 keeps 5 countries * 1 year * 3 indicators = 15 observation rows."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    result = ingest_sipri_yearbook_ch7(
        year=2024,
        pdf_path=pdf_path,
        catalog_path=sipri_yearbook_ch7_catalog_path,
    )
    assert result.countries == 5
    assert result.years == (2024,)
    assert result.observation_rows == 15


def test_ingest_sipri_yearbook_ch7_filters_to_other_year_returns_empty(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """year=2023 produces 0 observation rows and an empty wide frame;
    the orchestrator still writes the sources row and the manifest."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    result = ingest_sipri_yearbook_ch7(
        year=2023,
        pdf_path=pdf_path,
        catalog_path=sipri_yearbook_ch7_catalog_path,
    )
    assert result.countries == 0
    assert result.observation_rows == 0
    assert result.parquet_path.exists()


def test_ingest_sipri_yearbook_ch7_is_idempotent(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """Re-running ingest_sipri_yearbook_ch7 produces the same observation_rows
    count, the same source_id, and the parquet's mtime is the same (no re-write)."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    first = ingest_sipri_yearbook_ch7(
        pdf_path=pdf_path,
        catalog_path=sipri_yearbook_ch7_catalog_path,
    )
    second = ingest_sipri_yearbook_ch7(
        pdf_path=pdf_path,
        catalog_path=sipri_yearbook_ch7_catalog_path,
    )
    assert first.source_id == second.source_id
    assert first.observation_rows == second.observation_rows == 15


def test_ingest_sipri_yearbook_ch7_result_carries_attribution(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """SipriYearbookCh7IngestResult.attribution property returns
    SIPRI_YEARBOOK_CH7_ATTRIBUTION byte-for-byte;
    result.attribution == SIPRI_YEARBOOK_CH7_ATTRIBUTION."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    result = ingest_sipri_yearbook_ch7(
        pdf_path=pdf_path,
        catalog_path=sipri_yearbook_ch7_catalog_path,
    )
    assert result.attribution == SIPRI_YEARBOOK_CH7_ATTRIBUTION
    assert "SIPRI" in result.attribution
    assert "World Nuclear Forces" in result.attribution
    assert "Oxford University Press" in result.attribution


def test_ingest_sipri_yearbook_ch7_result_carries_pdf_pages_and_snapshot_year(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """SipriYearbookCh7IngestResult.pdf_pages_total is 1; snapshot_year is 2024;
    both surfaced from df.attrs (the PDF-specific audit fields)."""
    _init_test_db(database_url)
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    result = ingest_sipri_yearbook_ch7(
        pdf_path=pdf_path,
        catalog_path=sipri_yearbook_ch7_catalog_path,
    )
    assert result.pdf_pages_total == 1, "Fixture PDF is 1 page"
    assert result.snapshot_year == 2024, "YB24 fixture snapshot year is 2024"


def test_ingest_sipri_yearbook_ch7_result_field_count(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    database_url: str,
) -> None:
    """SipriYearbookCh7IngestResult has exactly 8 fields (matches
    sipri-yearbook-ch7.md §3.3 spec)."""
    fields = SipriYearbookCh7IngestResult.model_fields
    assert len(fields) == 8, (
        f"SipriYearbookCh7IngestResult should have 8 fields, got {len(fields)}: "
        f"{list(fields.keys())}"
    )
    expected_fields = {
        "source_id",
        "parquet_path",
        "observation_rows",
        "countries",
        "years",
        "indicators",
        "pdf_pages_total",
        "snapshot_year",
    }
    assert set(fields.keys()) == expected_fields


# ---------------------------------------------------------------------------
# Attribution / Rule #15 — 3 tests
# ---------------------------------------------------------------------------


def test_write_run_manifest(
    sipri_yearbook_ch7_pdf_dir: Path,
    sipri_yearbook_ch7_catalog_path: Path,
    isolated_data_lake: Path,
) -> None:
    """The run manifest is JSON next to the parquet and includes attribution,
    source_id, observation_rows, years, indicators, pdf_pages_total, snapshot_year."""
    pdf_path = sipri_yearbook_ch7_pdf_dir / "YB24 07 WNF.pdf"
    df = read_sipri_yearbook_ch7(pdf_path=pdf_path, catalog_path=sipri_yearbook_ch7_catalog_path)
    out = write_sipri_yearbook_ch7_parquet(df)

    result = SipriYearbookCh7IngestResult(
        source_id=1,
        parquet_path=out,
        observation_rows=15,
        countries=5,
        years=(2024,),
        indicators=3,
        pdf_pages_total=1,
        snapshot_year=2024,
    )
    manifest_path = write_sipri_yearbook_ch7_run_manifest(
        result,
        manifest_dir=isolated_data_lake / "data" / "processed" / SIPRI_YEARBOOK_CH7_SOURCE_KEY,
    )
    assert manifest_path.exists()
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert payload["source_id"] == 1
    assert payload["observation_rows"] == 15
    assert payload["years"] == [2024]
    assert payload["indicators"] == 3
    assert payload["attribution"] == SIPRI_YEARBOOK_CH7_ATTRIBUTION
    assert payload["pdf_pages_total"] == 1
    assert payload["snapshot_year"] == 2024


def test_attribution_matches_constant() -> None:
    """sipri_yearbook_ch7.attribution() == SIPRI_YEARBOOK_CH7_ATTRIBUTION;
    contains 'SIPRI', 'World Nuclear Forces', 'Yearbook 2024', 'Oxford University Press'."""
    assert attribution() == SIPRI_YEARBOOK_CH7_ATTRIBUTION
    assert "SIPRI" in attribution()
    assert "World Nuclear Forces" in attribution()
    assert "Oxford University Press" in attribution()


def test_sipri_yearbook_ch7_attribution_matches_attributions_doc() -> None:
    """SIPRI_YEARBOOK_CH7_ATTRIBUTION is a substring of docs/source-attributions.md
    (drift guard, same pattern as V-Dem, WGI, UCDP, SIPRI milex).

    Per AGENTS.md Always-On Rule #15, the code's attribution text and the
    doc's citation text must be byte-for-byte consistent. If either changes,
    both must be updated in the same commit.
    """
    doc_path = (
        Path(__file__).resolve().parents[1] / "docs" / "source-attributions.md"
    )
    doc_text = doc_path.read_text(encoding="utf-8")
    assert SIPRI_YEARBOOK_CH7_ATTRIBUTION in doc_text, (
        f"SIPRI_YEARBOOK_CH7_ATTRIBUTION is not present in {doc_path}. "
        "Update both in the same commit (Rule #15)."
    )


# ---------------------------------------------------------------------------
# CLI dispatch — 2 tests
# ---------------------------------------------------------------------------


def test_stage2_adapters_dispatch_table() -> None:
    """STAGE2_ADAPTERS['sipri_yearbook_ch7'] is sipri_yearbook_ch7.ingest_sipri_yearbook_ch7;
    the full key set is unchanged (25 keys, with sipri_yearbook_ch7 changing from None
    to the orchestrator). The existing 'sipri_yearbook_ch7': None entry is REPLACED,
    not duplicated."""
    assert STAGE2_ADAPTERS[SIPRI_YEARBOOK_CH7_SOURCE_KEY] is ingest_sipri_yearbook_ch7
    expected_keys = {
        "vdem",
        "world_bank_wdi",
        "world_bank_wgi",
        "ucdp",
        "sipri_milex",
        "sipri_yearbook_ch7",
        "pts",
        "undp_hdi",
        "who_gho_api",
        "polity_v",
        "pwt",
        "archigos",
        "reign",
        "leader_survival",
        "transparency_cpi",
        "fas",
        "wikidata_heads_of_state_government",
        "wikipedia_search_extract",
        "freedom_house",
        "imf_weo",
        "cow_mid",
        "cirights",
        "nti",
        "bti",
        "cia_world_leaders",
        "rsf_press_freedom",
    }
    assert set(STAGE2_ADAPTERS.keys()) == expected_keys


def test_cli_ingest_source_rejects_unknown() -> None:
    """The CLI's ingest-source command rejects unknown source keys."""
    runner = CliRunner()
    result = runner.invoke(app, ["ingest-source", "--source", "nope"])
    assert result.exit_code != 0


# ---------------------------------------------------------------------------
# Public surface — 1 test
# ---------------------------------------------------------------------------


def test_sipri_yearbook_ch7_module_public_surface() -> None:
    """The sipri_yearbook_ch7 module exports the items in __all__ from
    sipri-yearbook-ch7.md §3.3."""
    assert hasattr(sipri_yearbook_ch7, "SIPRI_YEARBOOK_CH7_ATTRIBUTION")
    assert hasattr(sipri_yearbook_ch7, "SIPRI_YEARBOOK_CH7_SOURCE_KEY")
    assert hasattr(sipri_yearbook_ch7, "IndicatorSpec")
    assert hasattr(sipri_yearbook_ch7, "SipriYearbookCh7IngestResult")
    assert hasattr(sipri_yearbook_ch7, "attribution")
    assert hasattr(sipri_yearbook_ch7, "ingest_sipri_yearbook_ch7")
    assert "SIPRI_YEARBOOK_CH7_ATTRIBUTION" in sipri_yearbook_ch7.__all__
    assert "SIPRI_YEARBOOK_CH7_SOURCE_KEY" in sipri_yearbook_ch7.__all__
    assert "IndicatorSpec" in sipri_yearbook_ch7.__all__
    assert "SipriYearbookCh7IngestResult" in sipri_yearbook_ch7.__all__
    assert "attribution" in sipri_yearbook_ch7.__all__
    assert "ingest_sipri_yearbook_ch7" in sipri_yearbook_ch7.__all__
