"""Client comparison delta test for the social-wellbeing scorer.

The client 2023 matrix is the **validation reference**, not an
evidence source (AGENTS.md always-on rule #6, requirement §3, §9,
§12). The deterministic scorer consumes the Stage 5 evidence
bundle and emits :attr:`ScoreResult.system_proposed_score_1_10`;
the client score is applied **after** the scorer returns to
populate :attr:`ScoreResult.score_delta_vs_client`.

This test pins the validation-only contract end-to-end:

1. The scorer is called with a non-client bundle — the same shape
   the production Stage 5 bundle builder would emit.
2. The client score is loaded from the existing vertical-slice
   parser (:func:`leaders_db.vertical_slice.parser.load_vertical_slice_client_rows`).
   No client row is added to the bundle's evidence observations.
3. The delta is computed as
   ``system_proposed_score_1_10 - client_score`` and set on the
   result via :func:`dataclasses.replace` so the original scorer
   payload is preserved.
4. The bundle's observations are inspected to assert no
   ``client_existing`` / ``client_matrix`` source key is present.

The fixture lives at
``tests/fixtures/vertical_slice/client_matrix_sample.xlsx`` (a
real-format subset of the client xlsx, generated by the
vertical-slice Phase C tests). The fixture sheet name matches
the parser's expected sheet (``Main``).

Style invariants (per ``docs/coding-guidelines.md``):

- ``from __future__ import annotations`` for forward-reference
  safety.
- Type hints on test parameters.
- No ``print()``, no ``TODO(debug)``, no scratch code.
"""

from __future__ import annotations

import dataclasses
from pathlib import Path

from leaders_db.score.category_plans import SOCIAL_WELLBEING_PLAN
from leaders_db.score.evidence import CategoryEvidenceBundle
from leaders_db.score.social_wellbeing import score_social_wellbeing
from leaders_db.vertical_slice.parser import load_vertical_slice_client_rows
from tests._social_wellbeing_factories import make_bundle, make_obs


def _fixture_xlsx() -> Path:
    """Return the path to the committed vertical-slice client xlsx fixture."""
    return Path(__file__).resolve().parent / "fixtures" / "vertical_slice" / (
        "client_matrix_sample.xlsx"
    )


def test_score_delta_vs_client_uses_parser_for_validation_only() -> None:
    """The client score is loaded by the parser and applied AFTER scoring.

    The test pins the validation-only contract end-to-end:

    1. Build a non-client bundle and run the scorer.
    2. Load the client score from the vertical-slice parser.
    3. Compute the delta and set it on a copy of the result.
    4. Verify no client observations were in the bundle and the
       delta field carries the expected value.
    """
    bundle = make_bundle(observations=(
        make_obs("undp_hdi_hdi", "undp_hdi", 0.78),
        make_obs("vdem_v2x_egal", "vdem", 0.55),
    ))

    # Sanity: the bundle has no client source keys.
    bundle_source_keys = {obs.source_key for obs in bundle.observations}
    assert "client_existing" not in bundle_source_keys
    assert "client_matrix" not in bundle_source_keys

    # 1. Run the deterministic scorer — client score is NOT input.
    result = score_social_wellbeing(bundle)
    assert result.score_delta_vs_client is None
    assert result.system_proposed_score_1_10 is not None

    # 2. Load the client score from the existing vertical-slice
    #    parser (validation-only fixture).
    client_rows = load_vertical_slice_client_rows(
        path=_fixture_xlsx(),
        sheet="Main",
        year=2023,
        iso3_scope=("MEX",),
    )
    assert len(client_rows) == 1
    client_row = client_rows[0]
    assert client_row.iso3 == "MEX"
    client_score = client_row.client_scores["social_wellbeing"]
    assert client_score is not None

    # 3. Compute delta AFTER scoring (validation only).
    delta = result.system_proposed_score_1_10 - client_score

    # 4. Apply delta via ``dataclasses.replace`` so the original
    #    scorer payload is preserved (audit trail).
    annotated = dataclasses.replace(result, score_delta_vs_client=delta)

    # The annotated result carries the delta; the original score
    # and the per-component breakdown are unchanged.
    assert annotated.score_delta_vs_client == delta
    assert annotated.system_proposed_score_1_10 == (
        result.system_proposed_score_1_10
    )
    assert annotated.normalized_score_0_1 == (
        result.normalized_score_0_1
    )
    assert annotated.components == result.components
    assert annotated.observation_refs == result.observation_refs


def test_score_delta_for_usa_loaded_from_parser() -> None:
    """The same flow works for a second ISO3 (USA) on the client fixture.

    The fixture carries USA at 8/10 for social_wellbeing; the
    deterministic scorer runs against a different bundle (because
    the bundle is per-country) and we compute the delta against
    the parser-loaded client value.
    """
    # A USA-shaped bundle (no client rows). USA is a high-income
    # OECD country with a high HDI; the fixture values are
    # illustrative.
    obs = (
        make_obs("undp_hdi_hdi", "undp_hdi", 0.95),
        make_obs("undp_hdi_life_expectancy", "undp_hdi", 0.85),
        make_obs("who_gho_under5_mortality", "who_gho_api", 0.95),
        make_obs("undp_hdi_gni_per_capita", "undp_hdi", 0.90),
        make_obs("wdi_gini_index", "world_bank_wdi", 0.70),
        make_obs("vdem_v2x_egal", "vdem", 0.75),
    )
    bundle = CategoryEvidenceBundle(
        country_iso3="USA",
        country_name="United States",
        leader_name="Joe Biden",
        year=2023,
        category_key="social_wellbeing",
        source_plan=SOCIAL_WELLBEING_PLAN,
        observations=obs,
    )

    result = score_social_wellbeing(bundle)
    assert result.is_insufficient_data is False
    assert result.system_proposed_score_1_10 is not None
    assert result.score_delta_vs_client is None

    client_rows = load_vertical_slice_client_rows(
        path=_fixture_xlsx(),
        sheet="Main",
        year=2023,
        iso3_scope=("USA",),
    )
    client_score = client_rows[0].client_scores["social_wellbeing"]
    assert client_score is not None

    delta = result.system_proposed_score_1_10 - client_score
    annotated = dataclasses.replace(result, score_delta_vs_client=delta)
    assert annotated.score_delta_vs_client == delta


def test_bundle_never_contains_client_observations_in_production_path() -> None:
    """The production path's bundle does not include client observations.

    This is a structural assertion: the bundle the scorer sees has
    only non-client source keys. The bundle builder is the
    gatekeeper (``EXCLUDED_SOURCE_KEYS`` in
    :mod:`leaders_db.score.source_plans`); the scorer can trust
    the bundle to be client-free.
    """
    bundle = make_bundle(observations=(
        make_obs("undp_hdi_hdi", "undp_hdi", 0.78),
        make_obs("vdem_v2x_egal", "vdem", 0.55),
    ))
    for obs in bundle.observations:
        assert obs.source_key not in {"client_existing", "client_matrix"}

    # And the scorer propagates that constraint to its components.
    result = score_social_wellbeing(bundle)
    for component in result.components:
        assert component.source_key not in {"client_existing", "client_matrix"}
