"""Constants for the clean SIPRI Yearbook Ch.7 source adapter."""

from __future__ import annotations

SIPRI_YEARBOOK_CH7_SOURCE_KEY = "sipri_yearbook_ch7"
SIPRI_YEARBOOK_CH7_ATTRIBUTION_KEY = "sipri_yearbook_ch7"
SIPRI_YEARBOOK_CH7_DEFAULT_VERSION = "YB2024 (data: January 2024)"
SIPRI_YEARBOOK_CH7_HOMEPAGE_URL = "https://www.sipri.org/yearbook/2024"
SIPRI_YEARBOOK_CH7_METADATA_NAME = "metadata.json"
SIPRI_YEARBOOK_CH7_PDF_NAME = "YB24 07 WNF.pdf"
SIPRI_YEARBOOK_CH7_PDF_ASSET_ID = (
    f"{SIPRI_YEARBOOK_CH7_SOURCE_KEY}:{SIPRI_YEARBOOK_CH7_PDF_NAME}"
)

SIPRI_YEARBOOK_CH7_OBSERVATION_FAMILY = "nuclear_country_year"
SIPRI_YEARBOOK_CH7_SUPPORTED_FAMILIES = (SIPRI_YEARBOOK_CH7_OBSERVATION_FAMILY,)
SIPRI_YEARBOOK_CH7_SNAPSHOT_YEAR = 2024
SIPRI_YEARBOOK_CH7_COVERAGE_START_YEAR = SIPRI_YEARBOOK_CH7_SNAPSHOT_YEAR
SIPRI_YEARBOOK_CH7_COVERAGE_END_YEAR = SIPRI_YEARBOOK_CH7_SNAPSHOT_YEAR

SIPRI_YEARBOOK_CH7_ATTRIBUTION_TEXT = (
    "SIPRI Yearbook 2024 Ch.7 "
    "(Stockholm International Peace Research Institute 2024)."
)

SIPRI_YEARBOOK_CH7_TRANSFORM_NAME = "sipri_yearbook_ch7_country_year_v1"
SIPRI_YEARBOOK_CH7_CHECKSUM_MISMATCH = "sipri_yearbook_ch7_checksum_mismatch"
SIPRI_YEARBOOK_CH7_LOCAL_FILES_INVALID = "sipri_yearbook_ch7_local_files_invalid"
SIPRI_YEARBOOK_CH7_METADATA_VERSION_MISMATCH = (
    "sipri_yearbook_ch7_metadata_version_mismatch"
)
SIPRI_YEARBOOK_CH7_UNSUPPORTED_VERSION = "unsupported_version"

SIPRI_YEARBOOK_CH7_INDICATORS = (
    "sipri_yearbook_ch7_nuclear_warheads_total_inventory",
    "sipri_yearbook_ch7_nuclear_warheads_deployed",
    "sipri_yearbook_ch7_nuclear_warheads_retired",
)

__all__ = [
    "SIPRI_YEARBOOK_CH7_ATTRIBUTION_KEY",
    "SIPRI_YEARBOOK_CH7_ATTRIBUTION_TEXT",
    "SIPRI_YEARBOOK_CH7_CHECKSUM_MISMATCH",
    "SIPRI_YEARBOOK_CH7_COVERAGE_END_YEAR",
    "SIPRI_YEARBOOK_CH7_COVERAGE_START_YEAR",
    "SIPRI_YEARBOOK_CH7_DEFAULT_VERSION",
    "SIPRI_YEARBOOK_CH7_HOMEPAGE_URL",
    "SIPRI_YEARBOOK_CH7_INDICATORS",
    "SIPRI_YEARBOOK_CH7_LOCAL_FILES_INVALID",
    "SIPRI_YEARBOOK_CH7_METADATA_NAME",
    "SIPRI_YEARBOOK_CH7_METADATA_VERSION_MISMATCH",
    "SIPRI_YEARBOOK_CH7_OBSERVATION_FAMILY",
    "SIPRI_YEARBOOK_CH7_PDF_ASSET_ID",
    "SIPRI_YEARBOOK_CH7_PDF_NAME",
    "SIPRI_YEARBOOK_CH7_SNAPSHOT_YEAR",
    "SIPRI_YEARBOOK_CH7_SOURCE_KEY",
    "SIPRI_YEARBOOK_CH7_SUPPORTED_FAMILIES",
    "SIPRI_YEARBOOK_CH7_TRANSFORM_NAME",
    "SIPRI_YEARBOOK_CH7_UNSUPPORTED_VERSION",
]
