"""Artifact writers for first-slice research runs."""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from leaders_db.sources.contracts import SourceAttribution, SourceId

from .models import (
    AnalyticalDatasetRow,
    EvidenceAcquisitionTask,
    EvidenceGapReport,
    Finding,
    InvestigationPlan,
    ResearchQuestion,
    evidence_query_to_dict,
)

CSV_COLUMNS = (
    "question_id",
    "row_scope_json",
    "concept_key",
    "value",
    "value_type",
    "unit",
    "source_id",
    "source_observation_ids",
    "coverage_status",
    "confidence_score",
    "warning_codes",
    "caveats",
    "provenance_json",
)

APPENDIX_COLUMNS = (
    "question_id",
    "row_scope_json",
    "concept_key",
    "coverage_status",
    "source_observation_ids",
    "source_id",
    "warning_codes",
    "caveats",
    "provenance_json",
)


def write_research_artifacts(
    *,
    output_root: Path,
    run_id: str,
    question: ResearchQuestion,
    plan: InvestigationPlan,
    gap_report: EvidenceGapReport,
    acquisition_tasks: tuple[EvidenceAcquisitionTask, ...],
    dataset_rows: tuple[AnalyticalDatasetRow, ...],
    findings: tuple[Finding, ...],
    attributions: tuple[SourceAttribution, ...] = (),
    direct_source_ids: tuple[SourceId, ...] = (),
) -> dict[str, Path]:
    """Write the research artifact set under ``output_root / run_id``."""

    output_dir = output_root / run_id
    output_dir.mkdir(parents=True, exist_ok=True)

    paths = {
        "question": output_dir / "question.json",
        "plan": output_dir / "plan.json",
        "gap_report": output_dir / "evidence-gap-report.json",
        "acquisition_tasks": output_dir / "acquisition-tasks.json",
        "dataset": output_dir / "analytical-dataset.csv",
        "appendix": output_dir / "evidence-appendix.csv",
        "findings": output_dir / "findings.json",
        "report": output_dir / "report.md",
        "manifest": output_dir / "manifest.json",
    }
    _write_model_json(paths["question"], question)
    _write_model_json(paths["plan"], plan)
    _write_model_json(paths["gap_report"], gap_report)
    _write_json(paths["acquisition_tasks"], [_dump_model(task) for task in acquisition_tasks])
    _write_dataset_csv(paths["dataset"], dataset_rows)
    _write_appendix_csv(paths["appendix"], dataset_rows)
    _write_json(paths["findings"], [_dump_model(finding) for finding in findings])
    _write_report(
        paths["report"], question, dataset_rows, findings, attributions, direct_source_ids
    )
    _write_json(paths["manifest"], _manifest(run_id, question, plan, paths, dataset_rows, findings))
    return paths


def _write_model_json(path: Path, model: BaseModel) -> None:
    _write_json(path, _dump_model(model))


def _write_json(path: Path, payload: Any) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_dataset_csv(path: Path, rows: tuple[AnalyticalDatasetRow, ...]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        for row in rows:
            writer.writerow(_csv_row(row))


def _write_appendix_csv(path: Path, rows: tuple[AnalyticalDatasetRow, ...]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=APPENDIX_COLUMNS)
        writer.writeheader()
        for row in rows:
            source = _csv_row(row)
            writer.writerow({column: source[column] for column in APPENDIX_COLUMNS})


def _write_report(
    path: Path,
    question: ResearchQuestion,
    rows: tuple[AnalyticalDatasetRow, ...],
    findings: tuple[Finding, ...],
    attributions: tuple[SourceAttribution, ...],
    direct_source_ids: tuple[SourceId, ...],
) -> None:
    lines = [
        f"# Research report: {question.display_text}",
        "",
        f"Question ID: `{question.question_id}`",
        "",
        "## Method",
        "",
        "This report was generated by deterministic registered planning. The runner "
        "selected the registered question/concept plan, queried the EvidenceRepository "
        "for stored observations, and wrote only traceable rows and findings. No live "
        "web acquisition, LLM/provider call, database persistence, or agent execution "
        "is performed in this increment.",
        "",
        "## Findings",
        "",
    ]
    for finding in findings:
        evidence_ids = ", ".join(f"`{item}`" for item in finding.source_observation_ids)
        if not evidence_ids:
            evidence_ids = "No direct evidence observation IDs."
        lines.extend(
            [
                f"- **{finding.finding_id}**: {finding.claim}",
                f"  - Evidence observation IDs: {evidence_ids}",
            ]
        )

    lines.extend(
        [
            "",
            "## Evidence and provenance",
            "",
            "Row-level provenance is written to `evidence-appendix.csv`; the main "
            "analytical table is `analytical-dataset.csv`.",
        ]
    )
    for row in rows:
        evidence_ids = ", ".join(f"`{item}`" for item in row.source_observation_ids)
        if not evidence_ids:
            evidence_ids = "none"
        lines.append(
            f"- `{row.concept_key}` / {row.coverage_status}: evidence IDs {evidence_ids}; "
            f"source `{row.source_id or 'none'}`."
        )

    warning_codes = sorted({code for row in rows for code in row.warning_codes})
    caveats = sorted({caveat for row in rows for caveat in row.caveats})
    finding_warnings = sorted({code for finding in findings for code in finding.warning_codes})
    finding_caveats = sorted({caveat for finding in findings for caveat in finding.caveats})
    lines.extend(["", "## Caveats and warnings", ""])
    if warning_codes or finding_warnings:
        lines.append("Warning codes: " + ", ".join(warning_codes + finding_warnings))
    else:
        lines.append("Warning codes: none.")
    if caveats or finding_caveats:
        lines.append("Caveats: " + "; ".join(caveats + finding_caveats))
    else:
        lines.append("Caveats: none beyond the deterministic stored-evidence boundary.")

    lines.extend(["", "## Source attributions", ""])
    attributed_slugs = {attribution.source_id.slug for attribution in attributions}
    if attributions:
        for attribution in attributions:
            suffix = f" ({attribution.citation_url})" if attribution.citation_url else ""
            license_text = (
                f" License: {attribution.license_name}." if attribution.license_name else ""
            )
            lines.append(
                f"- `{attribution.source_id.slug}`: "
                f"{attribution.text}{suffix}{license_text}"
            )
    else:
        lines.append(
            "No source attributions available from the EvidenceRepository for direct "
            "row source IDs in this run."
        )

    missing_slugs = tuple(
        source_id.slug
        for source_id in direct_source_ids
        if source_id.slug not in attributed_slugs
    )
    if missing_slugs:
        lines.append(
            "Missing source attributions for direct row source IDs: "
            + ", ".join(f"`{slug}`" for slug in missing_slugs)
            + "."
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _csv_row(row: AnalyticalDatasetRow) -> dict[str, Any]:
    return {
        "question_id": row.question_id,
        "row_scope_json": _stable_json(_dump_model(row.row_scope)),
        "concept_key": row.concept_key,
        "value": row.value,
        "value_type": row.value_type,
        "unit": row.unit,
        "source_id": row.source_id,
        "source_observation_ids": _stable_json(row.source_observation_ids),
        "coverage_status": row.coverage_status,
        "confidence_score": row.confidence_score,
        "warning_codes": _stable_json(row.warning_codes),
        "caveats": _stable_json(row.caveats),
        "provenance_json": _stable_json(row.provenance_json),
    }


def _manifest(
    run_id: str,
    question: ResearchQuestion,
    plan: InvestigationPlan,
    paths: dict[str, Path],
    dataset_rows: tuple[AnalyticalDatasetRow, ...],
    findings: tuple[Finding, ...],
) -> dict[str, Any]:
    return {
        "run_id": run_id,
        "question_id": question.question_id,
        "question_key": question.question_key,
        "evidence_query": evidence_query_to_dict(plan.evidence_query),
        "artifact_files": {key: path.name for key, path in sorted(paths.items())},
        "dataset_row_count": len(dataset_rows),
        "finding_count": len(findings),
    }


def _dump_model(model: BaseModel) -> dict[str, Any]:
    return model.model_dump(mode="json")


def _stable_json(payload: Any) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"))
